apiVersion: v1 # required
kind: Pod # required
metadata: # required
  name: nginx-pod
  labels:
    run: nginx-pod
    environment: dev
    app: nginx
  annotations:
    imageregistry: "https://hub.docker.com/"
spec: # required spec is the beginning of the block defining the desired state of the Pod object.
  containers:
  - name: nginx-pod
    image: nginx:1.22.1
    ports:
    - containerPort: 80
    resources:
      limits:
        nvidia.com/gpu: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    accelerator: nvidia-tesla-p100
status: {}
