apiVersion: v1
kind: Service
metadata:
  name: hello-world-np-svc
  namespace: k8stutorial
spec:
  selector:
    app: hello-world-np
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 32233
  type: NodePort # Services accessible from the external world.