apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-test
  namespace: k8stutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-test
  template:
    metadata:
      labels:
        app: worker-test
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: file-secret
      containers:
        - name: worker-test
          image: teklitb/worker-service2:latest
          volumeMounts:
            - mountPath: "/secret/secret-volume"
              name: secret-volume
              readOnly: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 25%
---
apiVersion: v1
kind: Secret
metadata:
  name: file-secret
  namespace: k8stutorial
stringData:
  hello.txt: Hello secret mounted as volume!