apiVersion: v1
kind: Service
metadata:
  name: green-web-svc
  namespace: k8stutorial
  labels:
    app: green-web
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: green-web